.TH n2o 1 "n2o 4.5.0" "Synrc Research Center" "N2O"
.SH NAME
n2o \- Protocol and Application Server
.SH INTRO
.LP
The \fIn2o\fR\& defines the way you define, confifure and run
arbitrary applications and protocols inside some hosts, into
which \fIn2o\fR\& is injected. They can be \fIcowboy\fR\& and \fIemqttd\fR\&.
Each application can spawn its instance in own way, like
web pages spawn WebSocket connections, workflow engines
spawn business proceseses and chat application spawns roster
and chatroom processes. This is managed by protocols.
.SH PROTOCOLS
.LP
While all application protocols in the system
are desired to be placed in the single effectful
environment or same error handling path, \fIn2o\fR\& defines
single protocol loop for all applications in its federation of protocols.
.LP
In core bundle \fIn2o\fR\& is shipped with NITRO and FTP protocols which
allows you to create real-time web applications with binary-based protocols,
priving also robust and performant upload client and file transfer protocol.
For bulding web based NITRO applications you need to include \fInitro\fR\& dependency.
.SH CONFIG
.LP
We usually store n2o configuration in root sys.config,
but you can use it whatever you like.
.LP
.nf
[{n2o,[{formatter,bert},
       {json,jsone},
       {pickler,n2o_secret},
       {erroring,n2o},
       {protocols,[n2o_ftp,n2o_nitro]},
       {filter,{n2o_proto,push}},
       {n2o,timer,{0,10,0}}]}].
.fi
.SH ALSO
.LP
\fB\fIn2o_format(1)\fR\&\fR\&, \fB\fIn2o_async(1)\fR\&\fR\&, \fB\fIn2o_proto(1)\fR\&\fR\&,
\fB\fIn2o_ftp(1)\fR\&\fR\&, \fB\fIn2o_nitro(1)\fR\&\fR\&
