.TH ftp.js 1 "ftp.js" "Synrc Research Center" "FTP.JS"
.SH NAME
ftp.js

.SH INTRO
.LP
The
\fIftp.js\fR\& module provides client FTP protocol implementation.

.SH ALSO
.LP
\fB\fIbert.js(1)\fR\&\fR\&, \fB\fIutf8.js(1)\fR\&\fR\&, \fB\fImq.js(1)\fR\&\fR\&, \fB\fInitro.js(1)\fR\&\fR\&, \fB\fIn2o.js(1)\fR\&\fR\&,