.TH heart.js 1 "heart.js" "Synrc Research Center" "HEART.JS"
.SH NAME
heart.js

.SH INTRO
.LP
The
\fIheart.js\fR\& module provides client HEART protocol implementation.
The size of
heart.js
is 1152 bytes.

.SH CONFIG
.LP
Configuration consists of:
1) current transport;
2) array of available transports;
3) reconnection delay;
4) threshold of maximum reconnects.
.nf
ct = 0;
transports = [ $ws ];
reconnectDelay = 1000;
maxReconnects = 100;
.fi

.SH TRANSPORT
.LP
Transport contains PING interval. On hearbeat ws.send('PING') is performed.
.nf
$ws = { heart: true,
interval: 5000,
creator: function(url) { },
onheartbeat: function() { } }
.fi

.SH CONNECTION
.nf
$conn = { onopen: nop,
onmessage: nop,
onclose: nop,
onconnect: nop,
send:  function(data) { },
close: function() { } }
.fi

.SH ALSO
.LP
\fB\fIbert.js(1)\fR\&\fR\&, \fB\fIutf8.js(1)\fR\&\fR\&, \fB\fImq.js(1)\fR\&\fR\&, \fB\fInitro.js(1)\fR\&\fR\&, \fB\fIn2o.js(1)\fR\&\fR\&