.TH ieee754.js 1 "ieee754.js" "Synrc Research Center" "IEEE754.JS"
.SH NAME
ieee754.js

.SH INTRO
.LP
The
\fIieee754.js\fR\& module provides IEEE-754 binary encoder/decoder.
This size of
ieee754.js
is 1404 bytes.

.SH API
read_Float(buffer, offset, isLE, mantis, len)
write_Float(buffer, value, offset, isLE, mantis, len)

.SH ALSO
.LP
\fB\fIbert.js(1)\fR\&\fR\&, \fB\fIheart.js(1)\fR\&\fR\&, \fB\fIn2o.js(1)\fR\&\fR\&,