.TH man/n2o.js 1 "man/n2o.js" "Synrc Research Center" "N2O.JS"
.SH NAME
man/n2o.js

.SH INTRO
.LP
The
\fIn2o.js\fR\& module provides N2O protocol loop at JavaScript side.
The size of
n2o.js
is 2120 bytes.

.SH CONFIG
.LP
This function creates a WebSocket raw connection to N2O WS and
sends
<
<"N2O,",Token/binary
>
> text packet
which invokes
\fINITRO\fR\& protocol page initialization.
.nf
active = false,
debug = false,
session = "sid",
protocol = window.location.protocol == 'https:' ? "wss://" : "ws://",
querystring = window.location.pathname + window.location.search,
host = window.location.hostname;
protos = [$bert];
.fi

.SH API
token()
.LP
Token returns chached in localStorage session token.
N2O_start()
.LP
This function creates a WebSocket raw connection to N2O WS and
sends
<
<"N2O,",Token/binary
>
> text packet
which invokes
\fINITRO\fR\& protocol page initialization.
.nf
function N2O_start() { }
.fi

.SH BERT
.nf
$bert.protos = [$io,$file];
$bert.on = function onbert(evt, cb) { }
.fi

.SH JSON
.nf
$client.on = function onclient(evt, callback) { }
.fi

.SH ALSO
.LP
\fB\fIutf8.js(1)\fR\&\fR\&, \fB\fIheart.js(1)\fR\&\fR\&, \fB\fInitro.js(1)\fR\&\fR\&, \fB\fIbert.js(1)\fR\&\fR\&,