.TH man/n2o_heart 1 "man/n2o_heart" "Synrc Research Center" "HEART"
.SH NAME
man/n2o_heart

.SH INTRO
.LP
The
\fIn2o_heart\fR\& module provides HEART protocol implementation.

.SH PING
.LP
Input Messages:
.nf
.fi
<
<"PING">>
<
<>>
.LP
Output Messages:
.nf
.fi
<
<"PONG">>
<
<>>

.SH ALSO
.LP
\fB\fIn2o_ftp(1)\fR\&\fR\&, \fB\fIn2o_nitro(1)\fR\&\fR\&,