.TH n2o_mqtt 1 "n2o_mqtt" "Synrc Research Center" "MQTT"
.SH NAME
n2o_mqtt

.SH INTRO
.LP
\fIn2o_mqtt\fR\& is an instance of
\fIn2o_pi\fR\& prorocess. In N2O
number of such instanses is usually equals to the number of cores.
.LP
There is two styles of embedding N2O: one is to perform N2O protocol loop inside
connection process (as in cowboy version); second is to spawn ring of n2o_pi
processes and handle all requests inside these processes (as in MQTT version). n2o_mqtt is
the protocol of such virtual node processes.

.SH PROTOCOL
.LP
On
init
n2o_mqtt makes connection to MQTT server.
On connection established in
#mqttc/2
it subscribes to events topic.
.nf
events/+/:name/#
.fi
.LP
After supscription all messages that are being sent to
events
topic are
passed as
#publish/2
where
\fIn2o_proto:info/3\fR\& protocol loop is
embedded as handler to that message.
.nf
#publish { topic   = [] :: binary(),
message = [] :: binary()}.
#mqttc { client :: pid(),
status :: connected }.
.fi
.LP
All the results go to
actions
topic:
.nf
actions/:vsn/:module/:client
.fi

.SH CONFIG
.LP
Service workers start MQTT clients with following config:
.nf
[{mqtt,[{host, "127.0.0.1"},
{client_id, Gnerated},
{clean_sess, false},
{logger, {console, error}},
{reconnect, 5}]}].
.fi

.SH ALSO
.L