.TH n2o_secret 1 "n2o_secret" "Synrc Research Center" "SECRET"
.SH NAME
n2o_secret

.SH INTRO
.LP
The
\fIn2o_secret\fR\& module provides AES/CBC-128 encoder/decoder.

.SH API
pickle(term()) -> binary().
.LP
Encodes the term.
depickle(binary()) -> term().
.LP
Decodes the term.
sid(term()) -> binary().
.LP
Returns HEX of first 10 bytes of HMAC/SHA256 signed seed with a secret.

.SH ALSO
.LP
\fB\fIn2o_bert(1)\fR\&\fR\&