.TH n2o_stream 1 "n2o_stream" "Synrc Research Center" "STREAM"
.SH NAME
n2o_stream

.SH INTRO
.LP
WebSocket
\fIn2o_stream\fR\& is implemented
cowboy_websocket_handler
behaviour for WS protocol
and
cowboy_http_handler
handler for XHR protocol. Both protocols are supported in single file.
This module is only for using N2O with
cowboy
web server.

.SH API
.LP
The n2o_proto protocol loop is compatible with cowboy and emqttd versions of N2O.
The main purpose of this API is to embed N2O into your functional endpoint.
In other cases it's called automatically by configuration.
websocket_info({ text | binary, binary() }, term(), term()) -> #reply{}.
.LP
The stream function is dedicated for
cowboy
version of n2o.
websocket_handle({ text | binary, binary() }, term(), term()) -> #reply{}.
.LP
This function is called on message arrival.
websocket_init(term(), term(), term()) -> #reply{}.
.LP
This function is called on init.
websocket_terminate(term(), term(), term()) -> #reply{}.
.LP
This function is called on terminate.
info(term(), term(), term()) -> #reply{}.
.LP
The info function is dedicated for
HTTP XHR
fallback.

.SH CONFIG
.nf
[{n2o,[{protocols,[n2o_nitro]},
{filter,{n2o_proto,push}}]}].
.fi

.SH ALSO
.L