.TH man/utf8.js 1 "man/utf8.js" "Synrc Research Center" "UTF8.JS"
.SH NAME
man/utf8.js

.SH INTRO
.LP
The
\fIutf8.js\fR\& module provides UTF-8 encoder/decoder.
The size of
utf8.js
is 227 bytes.

.SH API
utf8_enc(x)
.LP
Perform UTF-8 encoding.
utf8_dec(x)
.LP
Perform UTF-8 decoding.

.SH ALSO
.LP
\fB\fIbert.js(1)\fR\&\fR\&, \fB\fIheart.js(1)\fR\&\fR\&, \fB\fInitro.js(1)\fR\&\fR\&, \fB\fIn2o.js(1)\fR\&\fR\&,