.TH ftp.js 1 "ftp.js" "Synrc Research Center" "FTP.JS"
.SH NAME
ftp.js

.SH ВСТУП
.LP
Модуль
\fIftp.js\fR\& надає клієнтську реалізацію протоколу FTP.

.SH ALSO
.LP
\fB\fIbert.js(1)\fR\&\fR\&, \fB\fIutf8.js(1)\fR\&\fR\&, \fB\fImq.js(1)\fR\&\fR\&, \fB\fInitro.js(1)\fR\&\fR\&, \fB\fIn2o.js(1)\fR\&\fR\&