.TH heart.js 1 "heart.js" "Synrc Research Center" "HEART.JS"
.SH NAME
heart.js

.SH ВСТУП
.LP
Модуль
\fIheart.js\fR\& надає клієнтську реалізацію протоколу HEART.
Розмір
heart.js
— 1152 байти.

.SH КОНФІГУРАЦІЯ
.LP
Конфігурація складається з наступних елементів:
1) поточний транспорт;
2) масив доступних транспортів;
3) затримка повторного підключення;
4) максимальна кількість повторних підключень.
.nf
ct = 0;
transports = [ $ws ];
reconnectDelay = 1000;
maxReconnects = 100;
.fi

.SH ТРАСПОРТ
.LP
Транспорт містить інтервал PING. On hearbeat виконується команда ws.send('PING') .
.nf
$ws = { heart: true,
interval: 5000,
creator: function(url) { },
onheartbeat: function() { } }
.fi

.SH З'ЄДНАННЯ
.nf
$conn = { onopen: nop,
onmessage: nop,
onclose: nop,
onconnect: nop,
send:  function(data) { },
close: function() { } }
.fi

.SH ALSO
.LP
\fB\fIbert.js(1)\fR\&\fR\&, \fB\fIutf8.js(1)\fR\&\fR\&, \fB\fImq.js(1)\fR\&\fR\&, \fB\fInitro.js(1)\fR\&\fR\&, \fB\fIn2o.js(1)\fR\&\fR\&