.TH ieee754.js 1 "ieee754.js" "Synrc Research Center" "IEEE754.JS"
.SH NAME
ieee754.js

.SH ВСТУП
.LP
Модуль
\fIieee754.js\fR\& надає бінарний IEEE-754 кодер/декодер.
Розмір
ieee754.js
— 1404 байти.

.SH API
read_Float(buffer, offset, isLE, mantis, len)
write_Float(buffer, value, offset, isLE, mantis, len)

.SH ALSO
.LP
\fB\fIbert.js(1)\fR\&\fR\&, \fB\fIheart.js(1)\fR\&\fR\&, \fB\fIn2o.js(1)\fR\&\fR\&