.TH n2o.js 1 "n2o.js" "Synrc Research Center" "N2O.JS"
.SH NAME
n2o.js

.SH ВСТУП
.LP
Модуль
\fIn2o.js\fR\& надає протокольний цикл N2O на стороні JavaScript.
Розмір
n2o.js
— 2120 байт.

.SH КОНФІГУРАЦІЯ
.LP
.nf
active = false,
debug = false,
session = "sid",
protocol = window.location.protocol == 'https:' ? "wss://" : "ws://",
querystring = window.location.pathname + window.location.search,
host = window.location.hostname;
protos = [$bert];
.fi

.SH API
token()
.LP
Повертає токен сесії, закешований в localStorage.
N2O_start()
.LP
Ця функція створює сире WebSocket з'єднання з N2O WS
і надсилає текстовий пакет
<
<"N2O,",Token/binary
>
>,
який викликає ініціалізацію сторінки
\fINITRO\fR\& протоколом.
.nf
N2O_start();
.fi

.SH BERT
.nf
$bert.protos = [$io,$file];
$bert.on = function onbert(evt, cb) { }
.fi

.SH JSON
.nf
$client.on = function onclient(evt, callback) { }
.fi

.SH ALSO
.LP
\fB\fIutf8.js(1)\fR\&\fR\&, \fB\fIheart.js(1)\fR\&\fR\&, \fB\fInitro.js(1)\fR\&\fR\&, \fB\fIbert.js(1)\fR\&\fR\&