.TH n2o_mqtt 1 "n2o_mqtt" "Synrc Research Center" "MQTT"
.SH NAME
n2o_mqtt

.SH ВСТУП
.LP
\fIn2o_mqtt\fR\& є екземпляром
\fIn2o_pi\fR\& процесу.
В N2O кількість таких екземплярів зазвичай дорівнює кількості ядер.
.LP
Існує два способи вбудовування N2O: перший полягає у виконанні протокольного циклу N2O під час
процесу з'єднання (як в cowboy версії); другий — в створенні кільця n2o_pi процесів
та обробці всіх запитів всередині цих процесів (як в MQTT версії).
n2o_mqtt — це протокол таких процесів віртуальних вузлів.

.SH ПРОТОКОЛ
.LP
Реагуючи на повідомлення ініціалізації
init
n2o_mqtt створює з'єднання з MQTT сервером.
Після створення з'єднання, в
#mqttc/2
він підписується на канал events.
.nf
events/+/:name/#
.fi
.LP
Після підписки всі повідомлення, що надсилаються в канал
events
,
передаються в
#publish/2
, де цикл протоколу
\fIn2o_proto:info/3\fR\& вбудований у якості обробника цих повідомлень.
.nf
#publish { topic   = [] :: binary(),
message = [] :: binary()}.
#mqttc { client :: pid(),
status :: connected }.
.fi
.LP
Всі результати пересилаються в канал
actions
:
.nf
actions/:vsn/:module/:client
.fi

.SH КОНФІГУРАЦІЯ
.LP
Сервісні воркери запускать MQTT клієнти в наступній конфігурації:
.nf
[{mqtt,[{host, "127.0.0.1"},
{client_id, Generated},
{clean_sess, false},
{logger, {console, error}},
{reconnect, 5}]}].
.fi

.SH ALSO
.L