.TH n2o_auth 1 "n2o_auth" "Synrc Research Center" "AUTH"
.SH NAME
n2o_auth

.SH ВСТУП
.LP
Модуль
\fIn2o_auth\fR\& надає EMQ hook авторизації, який визначає
автопідписку клієнта на клієнтський топік.

.SH CALLBACK
check(#mqtt_client{},binary(),term()) -> ok | ignore.
.LP
Реалізація за замовчуванням виконує автоматичну підписку топіка клієнта на стороні сервера.
.nf
check(#mqtt_client{client_id = ClientId, username  = PageModule,
client_pid = ClientPid,
ws_initial_headers = _Headers}, Password, Listeners) ->
ClientId = ensure_id(Client),
case ClientId of
.fi
<
<"emqttd_", _/binary>> ->
emqttd_client:subscribe(ClientPid,
[{n2o:to_binary(["actions/1/",PageModule,"/",ClientId]), 2}]),
ignore;
_ -> ignore
end.

.SH ALSO
.LP
\fB\fIn2o(1)\fR\&\fR\&, \fB\fIn2o_proto(1)\fR\&\fR\&, \fB\fIn2o_mqtt(1)\fR\&\fR\&