.TH n2o_secret 1 "n2o_secret" "Synrc Research Center" "SECRET"
.SH NAME
n2o_secret

.SH ВСТУП
.LP
Модуль
\fIn2o_secret\fR\& надає AES/CBC-128 кодер/декодер.

.SH API
pickle(term()) -> binary().
.LP
Кодує вираз.
depickle(binary()) -> term().
.LP
Декодує вираз.
sid(term()) -> binary().
.LP
Повертає HEX перших 10 байтів HMAC/SHA256 підписаного зерна з секретом.

.SH ALSO
.LP
\fB\fIn2o_bert(1)\fR\&\fR\&