.TH n2o_heart 1 "n2o_heart" "Synrc Research Center" "HEART"
.SH NAME
n2o_heart

.SH ВСТУП
.LP
Модуль
\fIn2o_heart\fR\& забезпечує реалізацію протоколу HEART.

.SH PING
.LP
Вхідні Повідомлення:
.nf
.fi
<
<"PING">>
<
<>>
.LP
Вихідні Повідомлення:
.nf
.fi
<
<"PONG">>
<
<>>

.SH ALSO
.LP
\fB\fIn2o_ftp(1)\fR\&\fR\&, \fB\fIn2o_nitro(1)\fR\&\fR\&