.TH n2o_ftp 1 "n2o_ftp" "Synrc Research Center" "FTP"
.SH NAME
n2o_ftp

.SH ВСТУП
.LP
Модуль
\fIn2o_ftp\fR\& забезпечує реалізацію протоколу завантаження файлів.

.SH FTP
.nf
-record(ftp, { id       = [] :: [] | binary(),
sid      = [] :: [] | binary(),
filename = [] :: [] | binary(),
meta     = [] :: any(),
size     = [] :: [] | integer(),
offset   = [] :: [] | integer(),
block    = [] :: [] | integer(),
data     = [] :: [] | binary(),
status   = [] :: [] | binary() }).
.fi

.SH ALSO
.LP
\fB\fIn2o_heart(1)\fR\&\fR\&, \fB\fImq.js(1)\fR\&\fR\&, \fB\fIn2o_nitro(1)\fR\&\fR\&