.TH utf8.js 1 "utf8.js" "Synrc Research Center" "UTF8.JS"
.SH NAME
utf8.js

.SH ВСТУП
.LP
Модуль
\fIutf8.js\fR\& надає UTF-8 кодер/декодер.
Розмір
utf8.js
— 227 байт.

.SH API
utf8_enc(x)
.LP
Виконує кодування в UTF-8.
utf8_dec(x)
.LP
Виконує декодування з UTF-8.

.SH ALSO
.LP
\fB\fIbert.js(1)\fR\&\fR\&, \fB\fIheart.js(1)\fR\&\fR\&, \fB\fInitro.js(1)\fR\&\fR\&, \fB\fIn2o.js(1)\fR\&\fR\&